### ISSUE TITLE
Hosted Session Issue

### ISSUE THREAD

**Issue by DayLightsDream** [Mastercard-Gateway/gateway-java-sample-code#23]
Hi, I'm getting "Could not construct and store authentication result mastercard" error when I'm using Pay with 3DS.

JAR: 1.3
API: 57
ThreeDS: 1.3.0
Gateway: https://test-gateway.mastercard.com/

How to fix this problem?

**Comment by kjeedipally** [comment]
> Hi, I'm getting "Could not construct and store authentication result mastercard" error when I'm using Pay with 3DS.
> 
> JAR: 1.3
> API: 57
> ThreeDS: 1.3.0
> Gateway: https://test-gateway.mastercard.com/
> 
> How to fix this problem?

Hi, Can you provide more inputs please. How are you Authenticating to the Gateway and what is the merchant ID?

**Comment by kjeedipally** [comment]
@DayLightsDream  We are waiting for your inputs as we couldn't reproduce this issue. If we don't receive any inputs we have to close this issue.

**Comment by zurick9999** [comment]
We are not going to use hosted session anymore. Please close this, thanks.

**Comment by DayLightsDream** [comment]
We are not going to use hosted session anymore. Please close this, thanks
